### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by Jadfish** [nibustan/OOSE2015#7]
Items will be the parent class for Power Ups and Power Downs.

It will spawn from a destroyed box object. 

When a player character moves into the tile in which the item is located, the item will dissapear and change some variables for that player character.

Items will dissapear if they are hit by a bomb blast, so the players will have to be careful about where they place their bombs. On the other hand, it might be useful to a player if they can remove a Power Down item from his or her path, so that it doesn't obstruct their movement options when it matters.

**Comment by HansEmil** [comment]
Item layer is ready and functions for "random" drop are being worked on, aswell as each items gameplay effect.
