### ISSUE TITLE
Character

### ISSUE THREAD

**Issue by Jadfish** [nibustan/OOSE2015#8]
The players are characters. We need a character class.

Characters can move up, down, left and right. Each time the player presses a direction button on the keyboard, the character will move 1 tile in that direction. It will not be possible for the player to move halfway between two tiles, which means they will never get stuck on the central pillar tiles. This is useful to the player, since this will result in them not being caught in a bombblast because of inprecise controls.

They are able to place a bomb on the same tile that they are standing on.
Characters who place a bomb on a tile, can move away from that tile, but the bomb will be a wall if they try to go back on that tile again. If they move 1 tile away from the bomb tile in any direction, the bomb will be like a wall until it explodes.

Characters can't move through "wall" tiles.

Characters die when caught by a bomb blast.
When a character dies, they are sent back to their initial spawn point.

**Comment by HansEmil** [comment]
Characters must update for active fire in the 3 firelayers on their vector position, and take damage if true.
