### ISSUE TITLE
Bomb

### ISSUE THREAD

**Issue by Jadfish** [nibustan/OOSE2015#9]
We need a bomb parent class.

Bombs are placed on tiles. After 3 seconds, the bomb explodes in a bomb blast. The bomb blast sends an explosions in every direction (up, down, left, right). The bombblast will not move further if it is in front of a wall tile.
BombBlastsSize will be different in the bomb sub classes, but for now, its default range is 2 tiles in each direction. This will likely be for BombLevel01.

**Comment by HansEmil** [comment]
Bomb needs to chain (explode other bombs).

**Comment by HansEmil** [comment]
We could give the Bomb a collider as originally planned
